# Generated by Django 5.0 on 2024-09-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moovie_tablepy',
            old_name='title',
            new_name='Title',
        ),
    ]
