# Generated by Django 5.0 on 2024-09-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0002_rename_title_moovie_tablepy_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moovie_tablepy',
            old_name='success',
            new_name='Success',
        ),
    ]
