# Generated by Django 5.1.1 on 2024-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0003_rename_success_moovie_tablepy_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovie_tablepy',
            name='Img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
